=== mickaelseban/nurse-scheduler/files/schedule.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.dei.isep.ipp.pt/tap-2022" xmlns:tns="http://www.dei.isep.ipp.pt/tap-2022" elementFormDefault="qualified">
    <element name="shiftSchedule" type="tns:TShiftSchedule" />

    <complexType name="TShiftSchedule">
        <choice>
            <element name="day" type="tns:TDay" minOccurs="0" maxOccurs="unbounded"/>
        </choice>
    </complexType>

    <complexType name="TDay">
        <sequence>
            <element name="shift" type="tns:TShift" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="id" type="positiveInteger"/>
    </complexType>

    <complexType name="TShift">
        <sequence>
            <element name="nurse" type="tns:TNurse" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="id" type="string"/>
    </complexType>

    <complexType name="TNurse">
        <attribute name="name" type="string"/>
        <attribute name="role" type="string"/>
    </complexType>
</schema>

=== mickaelseban/nurse-scheduler/files/assessment/ms01/valid_09_out.xml
<?xml version="1.0" encoding="UTF-8"?>

<shiftSchedule xmlns="http://www.dei.isep.ipp.pt/tap-2022" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dei.isep.ipp.pt/tap-2022 ../../schedule.xsd ">
    <day id="1">
        <shift id="night">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="B"/>
            <nurse name="n3" role="B"/>
            <nurse name="n4" role="D"/>
        </shift>
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="A"/>
            <nurse name="n3" role="B"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n4" role="C"/>
            <nurse name="n5" role="D"/>
            <nurse name="n6" role="A"/>
            <nurse name="n7" role="B"/>
        </shift>
    </day>
    <day id="2">
        <shift id="night">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="B"/>
            <nurse name="n3" role="B"/>
            <nurse name="n4" role="D"/>
        </shift>
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="A"/>
            <nurse name="n3" role="B"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n4" role="C"/>
            <nurse name="n5" role="D"/>
            <nurse name="n6" role="A"/>
            <nurse name="n7" role="B"/>
        </shift>
    </day>
    <day id="3">
        <shift id="night">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="B"/>
            <nurse name="n3" role="B"/>
            <nurse name="n4" role="D"/>
        </shift>
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="A"/>
            <nurse name="n3" role="B"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n4" role="C"/>
            <nurse name="n5" role="D"/>
            <nurse name="n6" role="A"/>
            <nurse name="n7" role="B"/>
        </shift>
    </day>
    <day id="4">
        <shift id="night">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="B"/>
            <nurse name="n3" role="B"/>
            <nurse name="n4" role="D"/>
        </shift>
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="A"/>
            <nurse name="n3" role="B"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n4" role="C"/>
            <nurse name="n5" role="D"/>
            <nurse name="n6" role="A"/>
            <nurse name="n7" role="B"/>
        </shift>
    </day>
    <day id="5">
        <shift id="night">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="B"/>
            <nurse name="n3" role="B"/>
            <nurse name="n4" role="D"/>
        </shift>
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="A"/>
            <nurse name="n3" role="B"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n4" role="C"/>
            <nurse name="n5" role="D"/>
            <nurse name="n6" role="A"/>
            <nurse name="n7" role="B"/>
        </shift>
    </day>
    <day id="6">
        <shift id="night">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="B"/>
            <nurse name="n3" role="B"/>
            <nurse name="n4" role="D"/>
        </shift>
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="A"/>
            <nurse name="n3" role="B"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n4" role="C"/>
            <nurse name="n5" role="D"/>
            <nurse name="n6" role="A"/>
            <nurse name="n7" role="B"/>
        </shift>
    </day>
    <day id="7">
        <shift id="night">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="B"/>
            <nurse name="n3" role="B"/>
            <nurse name="n4" role="D"/>
        </shift>
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="A"/>
            <nurse name="n3" role="B"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n4" role="C"/>
            <nurse name="n5" role="D"/>
            <nurse name="n6" role="A"/>
            <nurse name="n7" role="B"/>
        </shift>
    </day>
</shiftSchedule>

=== mickaelseban/nurse-scheduler/files/assessment/ms01/valid_06_outDiff.xml
<?xml version='1.0' encoding="UTF-8"?>
<shiftSchedule 
xsi:schemaLocation="http://www.dei.isep.ipp.pt/tap-2022 ../../schedule.xsd " xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dei.isep.ipp.pt/tap-2022">
    <day id="1">
        <shift id="night">
            <nurse name="n1" role="A"/>
            <nurse name="n3" role="B"/>
            <nurse name="n4" role="B"/>
            <nurse name="n2" role="D"/>
        </shift>
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="A"/>
            <nurse name="n3" role="A"/>
            <nurse name="n4" role="B"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n1" role="C"/>
            <nurse name="n2" role="D"/>
            <nurse name="n3" role="A"/>
            <nurse name="n4" role="A"/>
        </shift>
    </day>
    <day id="2">
        <shift id="night">
            <nurse name="n1" role="A"/>
            <nurse name="n3" role="B"/>
            <nurse name="n4" role="B"/>
            <nurse name="n2" role="D"/>
        </shift>
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="A"/>
            <nurse name="n3" role="A"/>
            <nurse name="n4" role="B"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n1" role="C"/>
            <nurse name="n2" role="D"/>
            <nurse name="n3" role="A"/>
            <nurse name="n4" role="A"/>
        </shift>
    </day>
    <day id="3">
        <shift id="night">
            <nurse name="n1" role="A"/>
            <nurse name="n3" role="B"/>
            <nurse name="n4" role="B"/>
            <nurse name="n2" role="D"/>
        </shift>
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="A"/>
            <nurse name="n3" role="A"/>
            <nurse name="n4" role="B"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n1" role="C"/>
            <nurse name="n2" role="D"/>
            <nurse name="n3" role="A"/>
            <nurse name="n4" role="A"/>
        </shift>
    </day>
    <day id="4">
        <shift id="night">
            <nurse name="n1" role="A"/>
            <nurse name="n3" role="B"/>
            <nurse name="n4" role="B"/>
            <nurse name="n2" role="D"/>
        </shift>
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="A"/>
            <nurse name="n3" role="A"/>
            <nurse name="n4" role="B"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n1" role="C"/>
            <nurse name="n2" role="D"/>
            <nurse name="n3" role="A"/>
            <nurse name="n4" role="A"/>
        </shift>
    </day>
    <day id="5">
        <shift id="night">
            <nurse name="n1" role="A"/>
            <nurse name="n3" role="B"/>
            <nurse name="n4" role="B"/>
            <nurse name="n2" role="D"/>
        </shift>
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="A"/>
            <nurse name="n3" role="A"/>
            <nurse name="n4" role="B"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n1" role="C"/>
            <nurse name="n2" role="D"/>
            <nurse name="n3" role="A"/>
            <nurse name="n4" role="A"/>
        </shift>
    </day>
    <day id="6">
        <shift id="night">
            <nurse name="n1" role="A"/>
            <nurse name="n3" role="B"/>
            <nurse name="n4" role="B"/>
            <nurse name="n2" role="D"/>
        </shift>
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="A"/>
            <nurse name="n3" role="A"/>
            <nurse name="n4" role="B"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n1" role="C"/>
            <nurse name="n2" role="D"/>
            <nurse name="n3" role="A"/>
            <nurse name="n4" role="A"/>
        </shift>
    </day>
    <day id="7">
        <shift id="night">
            <nurse name="n1" role="A"/>
            <nurse name="n3" role="B"/>
            <nurse name="n4" role="B"/>
            <nurse name="n2" role="D"/>
        </shift>
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n2" role="A"/>
            <nurse name="n3" role="A"/>
            <nurse name="n4" role="B"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n1" role="C"/>
            <nurse name="n2" role="D"/>
            <nurse name="n3" role="A"/>
            <nurse name="n4" role="A"/>
        </shift>
    </day>
</shiftSchedule>

=== mickaelseban/nurse-scheduler/files/assessment/ms01/valid_01_out.xml
<?xml version="1.0" encoding="UTF-8"?>

<shiftSchedule xmlns="http://www.dei.isep.ipp.pt/tap-2022" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dei.isep.ipp.pt/tap-2022 ../../schedule.xsd ">

    <day id="1">
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n3" role="A"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n2" role="B"/>
        </shift>
    </day>
    <day id="2">
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n3" role="A"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n2" role="B"/>
        </shift>
    </day>
    <day id="3">
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n3" role="A"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n2" role="B"/>
        </shift>
    </day>
    <day id="4">
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n3" role="A"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n2" role="B"/>
        </shift>
    </day>
    <day id="5">
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n3" role="A"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n2" role="B"/>
        </shift>
    </day>
    <day id="6">
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n3" role="A"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n2" role="B"/>
        </shift>
    </day>
    <day id="7">
        <shift id="morning">
            <nurse name="n1" role="A"/>
            <nurse name="n3" role="A"/>
        </shift>
        <shift id="afternoon">
            <nurse name="n2" role="B"/>
        </shift>
    </day>
</shiftSchedule>
